-- MySQL Script generated by MySQL Workbench
-- Thu Apr 26 09:53:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gedesaft
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gedesaft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gedesaft` DEFAULT CHARACTER SET utf8 ;
USE `gedesaft` ;

-- -----------------------------------------------------
-- Table `gedesaft`.`affaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`affaires` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dossier` VARCHAR(45) NULL DEFAULT NULL,
  `lieu` VARCHAR(45) NULL DEFAULT NULL,
  `dateOuverture` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`personnes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`personnes` (
  `idPersonne` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `dateNaissance` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idPersonne`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`agents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`agents` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `grade` VARCHAR(45) NULL DEFAULT NULL,
  `personnes_idPersonne` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `personnes_idPersonne`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_agents_personnes1_idx` (`personnes_idPersonne` ASC),
  CONSTRAINT `fk_agents_personnes1`
    FOREIGN KEY (`personnes_idPersonne`)
    REFERENCES `gedesaft`.`personnes` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`agentaffecte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`agentaffecte` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dateAffectation` VARCHAR(45) NULL DEFAULT NULL,
  `affaires_id` INT(11) NOT NULL,
  `agents_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_AgentAffecte_affaires1_idx` (`affaires_id` ASC),
  INDEX `fk_AgentAffecte_agents1_idx` (`agents_id` ASC),
  CONSTRAINT `fk_AgentAffecte_affaires1`
    FOREIGN KEY (`affaires_id`)
    REFERENCES `gedesaft`.`affaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AgentAffecte_agents1`
    FOREIGN KEY (`agents_id`)
    REFERENCES `gedesaft`.`agents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`armes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`armes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `modele` VARCHAR(45) NULL DEFAULT NULL,
  `calibre` VARCHAR(45) NULL DEFAULT NULL,
  `noSerie` VARCHAR(45) NULL DEFAULT NULL,
  `personnes_idPersonne` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_armes_personnes1_idx` (`personnes_idPersonne` ASC),
  CONSTRAINT `fk_armes_personnes1`
    FOREIGN KEY (`personnes_idPersonne`)
    REFERENCES `gedesaft`.`personnes` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`armeimpliquees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`armeimpliquees` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dateImplication` DATE NULL DEFAULT NULL,
  `affaires_id` INT(11) NOT NULL,
  `armes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_affaires_has_armes_armes1_idx` (`armes_id` ASC),
  INDEX `fk_affaires_has_armes_affaires_idx` (`affaires_id` ASC),
  CONSTRAINT `fk_affaires_has_armes_affaires`
    FOREIGN KEY (`affaires_id`)
    REFERENCES `gedesaft`.`affaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_affaires_has_armes_armes1`
    FOREIGN KEY (`armes_id`)
    REFERENCES `gedesaft`.`armes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`suspect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`suspect` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `couleurCheveux` VARCHAR(45) NULL DEFAULT NULL,
  `couleurPeaux` VARCHAR(45) NULL DEFAULT NULL,
  `signeParticulier` VARCHAR(45) NULL DEFAULT NULL,
  `taille` INT(11) NULL DEFAULT NULL,
  `personnes_idPersonne` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `personnes_idPersonne`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_suspect_personnes1_idx` (`personnes_idPersonne` ASC),
  CONSTRAINT `fk_suspect_personnes1`
    FOREIGN KEY (`personnes_idPersonne`)
    REFERENCES `gedesaft`.`personnes` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`suspectimpliques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`suspectimpliques` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dateImplication` VARCHAR(45) NULL DEFAULT NULL,
  `affaires_id` INT(11) NOT NULL,
  `suspect_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_suspectImpliques_affaires1_idx` (`affaires_id` ASC),
  INDEX `fk_suspectImpliques_suspect1_idx` (`suspect_id` ASC),
  CONSTRAINT `fk_suspectImpliques_affaires1`
    FOREIGN KEY (`affaires_id`)
    REFERENCES `gedesaft`.`affaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suspectImpliques_suspect1`
    FOREIGN KEY (`suspect_id`)
    REFERENCES `gedesaft`.`suspect` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`temoins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`temoins` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `personnes_idPersonne` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `personnes_idPersonne`),
  INDEX `fk_temoins_personnes1_idx` (`personnes_idPersonne` ASC),
  CONSTRAINT `fk_temoins_personnes1`
    FOREIGN KEY (`personnes_idPersonne`)
    REFERENCES `gedesaft`.`personnes` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`temoinsimpliques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`temoinsimpliques` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dateDeposition` DATE NULL DEFAULT NULL,
  `deposition` VARCHAR(45) NULL DEFAULT NULL,
  `affaires_id` INT(11) NOT NULL,
  `temoins_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_temoinsImpliques_affaires1_idx` (`affaires_id` ASC),
  INDEX `fk_temoinsImpliques_temoins1_idx` (`temoins_id` ASC),
  CONSTRAINT `fk_temoinsImpliques_affaires1`
    FOREIGN KEY (`affaires_id`)
    REFERENCES `gedesaft`.`affaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_temoinsImpliques_temoins1`
    FOREIGN KEY (`temoins_id`)
    REFERENCES `gedesaft`.`temoins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`vehicules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`vehicules` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `marque` VARCHAR(45) NULL DEFAULT NULL,
  `modele` VARCHAR(45) NULL DEFAULT NULL,
  `immatriculation` VARCHAR(45) NULL DEFAULT NULL,
  `couleur` VARCHAR(45) NULL DEFAULT NULL,
  `personnes_idPersonne` INT(11) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_vehicules_personnes1_idx` (`personnes_idPersonne` ASC),
  CONSTRAINT `fk_vehicules_personnes1`
    FOREIGN KEY (`personnes_idPersonne`)
    REFERENCES `gedesaft`.`personnes` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`vehiculesimpliques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`vehiculesimpliques` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dateImplication` DATE NULL DEFAULT NULL,
  `vehicules_id` INT(11) NOT NULL,
  `affaires_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicules_has_affaires_affaires1_idx` (`affaires_id` ASC),
  INDEX `fk_vehicules_has_affaires_vehicules1_idx` (`vehicules_id` ASC),
  CONSTRAINT `fk_vehicules_has_affaires_affaires1`
    FOREIGN KEY (`affaires_id`)
    REFERENCES `gedesaft`.`affaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicules_has_affaires_vehicules1`
    FOREIGN KEY (`vehicules_id`)
    REFERENCES `gedesaft`.`vehicules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`victimes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`victimes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vivant` TINYINT(4) NULL DEFAULT NULL,
  `personnes_idPersonne` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `personnes_idPersonne`),
  INDEX `fk_victimes_personnes1_idx` (`personnes_idPersonne` ASC),
  CONSTRAINT `fk_victimes_personnes1`
    FOREIGN KEY (`personnes_idPersonne`)
    REFERENCES `gedesaft`.`personnes` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gedesaft`.`victimesimpliques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gedesaft`.`victimesimpliques` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `dateAgression` VARCHAR(45) NULL DEFAULT NULL,
  `typeAgression` VARCHAR(45) NULL DEFAULT NULL,
  `affaires_id` INT(11) NOT NULL,
  `victimes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_victimesImpliques_affaires1_idx` (`affaires_id` ASC),
  INDEX `fk_victimesImpliques_victimes1_idx` (`victimes_id` ASC),
  CONSTRAINT `fk_victimesImpliques_affaires1`
    FOREIGN KEY (`affaires_id`)
    REFERENCES `gedesaft`.`affaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_victimesImpliques_victimes1`
    FOREIGN KEY (`victimes_id`)
    REFERENCES `gedesaft`.`victimes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
